### PR TITLE
Add equals to kin accounts impl

### PR DESCRIPTION
**Pull request by OrenZak**
https://stackoverflow.com/a/11010650/2775465

### CODE REVIEW

**Review by drEfrati — COMMENTED** [review]
Classes that override the Object.equals() method must also override the Object.hashCode() method. The java.lang.Object class requires that any two objects that compare equal using the equals() method must produce the same integer result when the hashCode() method is invoked on the objects

**Review by drEfrati — COMMENTED** [review]
Add also instanceof check for both

**Comment by OrenZak** [comment]
@drEfrati there is a class check -> `getClass() != obj.getClass()`, i added hashCode

**Comment by drEfrati** [comment]
instanceof approach is favoured  because when we use getClass approach, you have the restriction that objects are only equal to other objects of the same class, the same run time type. 

Maybe in our case it is ok to leave it like this.

**Review by drEfrati — APPROVED** [review]

**Comment by drEfrati** [comment]
Wait for Rizgan to also give a review

**Review by yosriz — APPROVED** [review]
👍👍 @OrenZak we're grateful for your contributions!

**Pull request merged**
